# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Print task commands
    cmds:
      - task -a
    silent: true

  help:mod:
    desc: Help with mod
    cmds:
      - go help mod
      - go help mod init
    summary: |
      Displays help for the mod and init

  setup:uv:
    desc: Init UV for Python
    cmds:
      - uv init

  add:go-lint:
    desc: Install better golang lint library
    cmds:
      - brew install golangci-lint

  add:go-pkg:
    desc: Intall package documentation library
    cmds:
      - go install golang.org/x/pkgsite/cmd/pkgsite@latest

  setup:go:
    desc: Set up go development environment
    cmds:
      - go mod init github.com/thepseudocodeus/{{.CLI_ARGS}}

  test:hello:
    cmds:
      - go test

  run:hello:
    cmds:
      - go run hello.go

  run:tests:
    cmds:
      - go test ./hello -v
      - go test ./integers -v
      - go test ./iteration -v

  run:benchmarks:
    cmds:
      - go test -bench=. ./iteration
